feature/13_userProfile
t-systems-on-site-services-gmbh/BookABooth pull request #34
Opened 2024-11-11 14:13 UTC by finnG030702

Profil für Benutzer hinzugefügt, mit Daten für Benutzer und Unternehmen.
Wenn der Nutzer Adminrechte hat, wird der Teil für Unternehmen ausgeblendet.
Außerdem Buttons für
- Buchung bestätigen
- Buchung stornieren
- Von Warteliste entfernen
- Konto löschen
eingefügt. Der Button zum Konto löschen fordert auch ein Passwort und überprüft dieses, gelöscht wird aber noch nichts.
Das Logo des Unternehmens kann auch hochgeladen werden.
Jetzt auch mit Rebase, sodass eigentlich alles konfliktfrei funktionieren sollte.

2024-11-12 10:48 UTC, finnG030702 commented on src/main/java/de/tsystems/onsite/bookabooth/service/UserService.java
> +            user.setLogin(userProfileDTO.getUser().getLogin().toLowerCase());
Kann man, ist jetzt auch drin. Es gab die Methode userDTOToUser, aber die funktioniert nur mit dem AdminUserDTO und anstatt die umzuschreiben habe ich lieber eine eigene toEntity-Methode geschrieben, die mit dem UserProfileDTO funktioniert.

2024-11-12 10:49 UTC, finnG030702 commented on src/main/java/de/tsystems/onsite/bookabooth/service/UserService.java
> +                            company.setName(userProfileDTO.getCompany().getName());
Kann man, tut es jetzt auch. Hier musste ich nicht mal eine eigene Methode schreiben, da gab es eine toEntity, die funktioniert hat.

2024-11-12 10:51 UTC, finnG030702 commented on src/main/java/de/tsystems/onsite/bookabooth/service/UserService.java
> +    public void updateWaitingList(UserProfileDTO userProfileDTO) {
Das war die erste Methode für diese Buttons auf dem Profil, die ich implementiert habe, weshalb die einfach viel zu groß war. Jetzt ist die deutlich komprimierter. Der Name ist immer noch updateWaitingList, bisher benutze ich die aber nur, um Nutzer aus der Liste zu entfernen.

2024-11-12 10:52 UTC, finnG030702 commented on src/main/java/de/tsystems/onsite/bookabooth/web/rest/AccountResource.java
> +    public ResponseEntity<?> getUserProfile(Authentication authentication) {
Nur ResponseEntity hat bei mir eine Warnung ausgegeben, aber weil ich jetzt eine AccountResourceException zurück gebe (also wie im nächsten Change), konnte ich jetzt ResponseEntity<UserProfileDTO> nehmen

2024-11-12 10:55 UTC, finnG030702 commented on src/main/java/de/tsystems/onsite/bookabooth/web/rest/AccountResource.java
> +            throw new EmailAlreadyUsedException();
Für diese und die anderen beiden Methoden habe ich jetzt eine neue InvalidEmailException geschrieben. Sie wird ja wirklich nicht bereits verwendet, sondern stimmt nicht überein, ist also ungültig. Außerdem habe ich die Methoden noch etwas reduziert, weil ich da so häufig nach dem User gefragt habe.

2024-11-12 10:56 UTC, finnG030702 commented on src/main/java/de/tsystems/onsite/bookabooth/web/rest/AccountResource.java
> +            System.out.println("Das Passwort stimmt überein.");
Log.debug() funktioniert in der Klasse irgendwie nicht. Aber ist auch nicht so wichtig, das war hauptsächlich da drin, damit ich kontrollieren kann, dass die Klasse in die if geht und das tut sie. Also kann die Printline jetzt weg und später können da die Delete-Methoden rein.

2024-11-12 10:58 UTC, finnG030702 commented on src/main/webapp/app/account/settings/settings.component.ts
> +    const isChecked = computed(() => {
Schon, aber eigentlich ist es ja auch nur ein True oder False-Wert, über den ich halt diesen Text gepackt habe, damit es für den User verständlicher ist. Jetzt heißt die Variable onExhibitionList, was zwar immer noch sehr nach Boolean klingt, aber wenigstens etwas präziser ist.

2024-11-14 07:55 UTC, gricklom requested changes

2024-11-14 07:55 UTC, gricklom commented on src/main/java/de/tsystems/onsite/bookabooth/service/UserService.java
> +    public void updateWaitingList(UserProfileDTO userProfileDTO) {
Dann wäre ein besserer Name `removeFromWaitingList()`. Oder du behälst den Namen bei und fügst einen Parameter `boolean waitingList` hinzu. Den Parameter nutzt du dann beim Aufruf von `company.setWaitingList()`.

2024-11-14 07:55 UTC, gricklom commented on src/main/java/de/tsystems/onsite/bookabooth/service/UserService.java
> +            user.setLogin(userProfileDTO.getUser().getLogin().toLowerCase());
Jetzt nutzt du zwar den Mapper, aber du holst dir anschließend trotzdem aus dem vom Mapper gelieferten Objekt alle Attribute einzeln raus, um sie in der Entity zu aktualisieren. Das sollte der Mapper für dich schon erledigen. Den Mapper musst du entsprechend erweitern. Schau dir mal [3.6 Updating existing bean instances](https://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances) in der MapStruct-Doku an.

2024-11-14 07:55 UTC, gricklom commented on src/main/java/de/tsystems/onsite/bookabooth/service/UserService.java
> +                            company.setName(userProfileDTO.getCompany().getName());
Jetzt nutzt du zwar den Mapper, aber du holst dir anschließend trotzdem aus dem vom Mapper gelieferten Objekt alle Attribute einzeln raus, um sie in der Entity zu aktualisieren. Das sollte der Mapper für dich schon erledigen. Den Mapper musst du entsprechend erweitern. Schau dir mal [3.6 Updating existing bean instances](https://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances) in der MapStruct-Doku an.

2024-11-14 12:22 UTC, gricklom approved these changes

2024-11-14 12:22 UTC, merged